version: 0.0
os: linux 

#배포한 파일 위치 지정 
files:
  - source: /
    destination: /home/ec2-user/codedeploy
    overwrite: true

#배포한 파일이 ec2-user 권한으로 적용됨
permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user

